In [1]:
import numpy as np

In [16]:
def sigmoid(w,x):
    wt=-w.T@x
    return 1/(1+np.exp(wt))

In [31]:
def compute_gradient(X,Y,w):
    m=X.shape[0]
    for i in range(m):        
        return X.T@(sigmoid(w,X[i])-Y)/m

In [4]:
X=np.random.random((5,4))
X

array([[0.71795756, 0.17066565, 0.33424273, 0.25940916],
       [0.23209487, 0.08999136, 0.66643912, 0.60513358],
       [0.36587955, 0.45292047, 0.11356539, 0.3832091 ],
       [0.06416446, 0.56512939, 0.90451282, 0.71910281],
       [0.41524092, 0.55444186, 0.64592531, 0.69921834]])

In [7]:
Y=np.random.randint(0,10,(5,1))
Y

array([[0],
       [7],
       [6],
       [9],
       [3]])

In [8]:
w=np.random.random((4,1))
w

array([[0.84261738],
       [0.13870393],
       [0.11797718],
       [0.62586358]])

In [28]:
hx=np.zeros((4,5))
hx[2]

array([0., 0., 0., 0., 0.])

In [30]:
compute_gradient(X,Y,w)

array([[-0.87855832],
       [-1.76405325],
       [-2.71381044],
       [-2.64959966]])